# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# Author: Mykhailo Datsyk
# Contact: https://www.linkedin.com/in/mykhailo-datsyk/
#
# YOU SHOULD MERGE these entries into your engine_locations.yml environment 
# file, as
# THIS FILE BY ITSELF WILL NOT WORK 
# These are the additions to get cinema engine up and running with the 
# default tk-apps for this environment

################################################################################

# -- Cinema
engines.tk-cinema.location:
  type: github_release
  organization: mikedatsik
  repository: tk-cinema
  version: v1.0.0
